version: '3.8'

services:

  #PHP Service
  app:
    container_name: "app-laravel-simple-projects"
    build:
      context: "./.docker/app/"
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - "./:/var/www/html"
    depends_on:
      - mysql

  #Nginx Service
  webserver:
    container_name: "webserver-laravel-simple-projects"
    image: "nginx"
    restart: unless-stopped
    ports:
      # - "${APP_PORT}:80"
      - "80:80"
      - "6001:6001"
    volumes:
      - "./:/var/www/html"
      - "./.docker/server/nginx.conf:/etc/nginx/conf.d/default.conf"

  # DB UI management service
  myadmin:
    container_name: "myadmin-laravel-simple-projects"
    image: "phpmyadmin:latest"
    restart: unless-stopped
    ports:
      # - ${ADMINER_PORT}:8080
      - "85:80"
    depends_on:
      - mysql

  #MySQL Service
  mysql:
    container_name: "mysql-laravel-simple-projects"
    image: "mysql:8.0"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./.docker/data/:/var/lib/mysql/"
